### ISSUE TITLE
Suggestion - Clock Application

### ISSUE THREAD

**Issue by TreeBaron** [sugarlabs/sugar#760]
Clock Application - Toggling time to speech button does not result in any icon change. It’s impossible to tell that the button is actually a toggle and not a normal button. I suggest adding an icon that indicates when it is toggled.

**Comment by quozl** [comment]
On Ubuntu 16.04 with Sugar 0.110 there is an icon toggle state change of the background.

On Fedora 25 with Sugar 0.108 there is no change to icon background.

This was fixed in https://github.com/sugarlabs/sugar-artwork/commit/8448b7db48e26e11785c8d827304a0aae025615a#diff-bbfc34d1e3e9c4a2103160ff4a5fc172 and released in Sugar 0.110.

Please upgrade to Sugar 0.110, thanks.
