### ISSUE TITLE
Translator Malfunction 

### ISSUE THREAD

**Issue by jakeelove** [sugarlabs/sugar#767]
Update: Version: 0.108.1 windows x86_64 (64-bit)
Activity: Words
Activity Version: 21
Translating from English to Hindi, the translator reads an English phrase instead of reading the Hindi translation of the word. However, this only happens if the translated word and phrase are on different lines. If they are on the same line then it works fine. I'm not sure how to take a video of my problem without using another device. 

[Translator_Bugg (1).zip](https://github.com/sugarlabs/sugar/files/1051003/Translator_Bugg.1.zip)

**Comment by quozl** [comment]
Thanks for the bug report, but could you please add more detail;

* version of Sugar,
* name of the activity,
* version of the activity, use hotkeys F3 ctrl+2 to list versions,

The video is out of focus and I can't tell from it what the activity is.

Use alt+1 to make a screenshot rather than a mobile phone.
