### ISSUE TITLE
Web Browser Activity failing to start

### ISSUE THREAD

**Issue by fileoffset** [sugarlabs/sugar#768]
Hi,

I installed Sugar via APT as the guide says for Ubuntu: apt install sucrose

After installing on a fresh Ubuntu 17 install, I was able to boot into Sugar, and all the preinstalled Activities worked fine _except_ for the Web Browser.

Every time you tried to load it, it would just say "Browser failed to load".

I traced the error to an import in the Browser.activity via a stacktrace in log file. It failed on:

webactivity.py:
from collabwrapper.collabwrapper import CollabWrapper

I fixed this by doing the following:

sudo touch collabwrapper/__init__.py

Adding this ticket so it can be fixed properly in the main branch so no one else has this problem.

HTH

**Comment by quozl** [comment]
Yes, a well known problem.  Was fixed in Debian bug 848840 with Debian package version 200+20170502-1, which is also in Ubuntu 17.10.  We didn't have the problem at OLPC because we were using a custom package, and we're now using 201.2.  You can get 201.2 at http://people.sugarlabs.org/~quozl/Browse-201.2.xo but you'll need to install it with `sugar-install-bundle` because of a MIME type problem in Browse-200.

**Comment by fileoffset** [comment]
I have been trying to figure out why none of the Activities downloaded 
through the Browser were installing. I was just looking through logs 
saying no valid mimetype handler, so I think I've hit that bug as well hah.

Updating as suggested fixed that, thanks so much!

**Comment by quozl** [comment]
Yes, that one was fixed in two patches;
* https://github.com/sugarlabs/browse-activity/commit/16d967166aeb793f94403c5ccb262e10bf4a0342 (the MIME type was usually wrong in the server response, even from activities.sugarlabs.org, https://github.com/sugarlabs/aslo/issues/13)
* https://github.com/sugarlabs/browse-activity/commit/4a6825a80c1ca8aacbf0f70d0a71c331b4940527 (mistake in merging lost the open in journal button).
