### ISSUE TITLE
SOAS liveinst fails with "gcore exited with status 256"

### ISSUE THREAD

**Issue by risole** [sugarlabs/sugar#773]
Can run SOAS by booting from USB stick, but installing to hard drive fails.

Running the liveinst command as per https://wiki.sugarlabs.org/go/Tutorials/Installation/Install_with_liveinst results in "No protocol specified; Anaconda received signal 11! gcore exited with status 256".

This is using http://wiki.sugarlabs.org/go/Sugar_on_a_Stick/Downloads x86_64 with SOAS released on 11 July 2017 with Fedora 26. Bootable USB stick created with Rufus https://rufus.akeo.ie on win10.

Hardware is a Laptop: HP Stream 14-ax010nr intel celeron N3060 1.6GHz cpu, 4096mb ram, and 32 gb SSD HD. Goal is to have this machine dual-booting win10 (for firmware updates) and SOAS from the hard drive (solid state drive or SSD).

**Comment by quozl** [comment]
Won't fix, as `liveinst` is not part of Sugar, but is part of Fedora instead.

However, here's a few other things to try;

Try the Fedora 27 SoaS ISOs.  They may have fixed a problem, or they may be no different.

Use the (Red Hat Bugzilla)[https://bugzilla.redhat.com] to report this problem with `liveinst` on Fedora SoaS.

Signal 11 from Anaconda can also occur if there are RAM problems, so you might exclude that possibility using `memtest` run from ISO.  On IRC someone gave this kind of answer and pointed you to a (CentOS Installation Guide)[https://www.centos.org/docs/5/html/5.2/Installation_Guide/ch14s01s01.html] chapter, but I'm not sure if you stayed long enough to see that.

You might try installing Fedora 26 instead, the workstation ISO, then install the Sugar desktop using the instructions on the [Fedora](https://wiki.sugarlabs.org/go/Fedora#Using_Sugar_as_a_Desktop_Environment) page on our Wiki.

Alternatively, you might try the Sugar Live Build which is based on Debian, and is a more recent version of Sugar.  See [0.112](https://wiki.sugarlabs.org/go/0.112#How_to_test.3F_2).

Ask any questions to clarify the above, then after a while we'll close this issue because it isn't something we can fix in Sugar itself.

**Comment by risole** [comment]
Thanks very much for speedy and detailed reply. Sorry I missed the IRC reply. The IRC web client kept dropping the server connection.

I'm downloading http://people.sugarlabs.org/~quozl/sugar-live-build-20171009/ now. If that doesn't work for me then I'll try the Fedora 7 SoaS ISO.

Thanks again. Sugar looks wonderful!

**Comment by risole** [comment]
Thanks again for the suggestions. After I disabled secure boot and enabled legacy mode in this laptop bios boot settings, the 0.112 image did install onto a USB flash drive with Rufus and did boot for me. But now how do I install Sugar to the hard drive? There is no "liveinst" command on this image, and I'm having trouble finding the wiki instructions for doing this.

**Comment by quozl** [comment]
Sorry, it is not documented at Sugar Labs because we just borrowed the downstream distribution method.  Check the boot menu.  It follows unchanged a tradition of Debian Live Builds, and has an option to install or graphical install, thus;

![sugar-live-build](https://user-images.githubusercontent.com/2936481/32680095-34d5f984-c6bd-11e7-8c9b-80977b70f4f9.png)

In my testing it does not work on every EFI BIOS system, but does work on other systems.

You might also search for "how to install a debian live build?"

You might check Fedora SoaS again with secure boot disabled and legacy mode enabled, in case that was a cause of your original problem.

**Comment by risole** [comment]
Installing this to HD worked for me. Thanks for all the help.

I'm finding though that many of the activities won't start or crash frequently. Is this because 0.112 has not yet been fully tested? I'm also finding that many of the activities available at https://activities.sugarlabs.org/en-US/sugar/ are 2 or more years old (eg. Recently Added
added 07/26/2014
Comodo added 07/15/2014")

For a 7yo kid, which version of Sugar would you recommend for the sake of stability and educational value?

**Comment by quozl** [comment]
Every activity starts and is stable in that build, and I tested that before I published it.  Given your earlier signal 11 from anaconda, your system has a thermal, CPU, or a RAM fault yet to be diagnosed in full.  Please run a memory test for a few hours and report the result.

Yes, many activities at activities.sugarlabs.org have not been updated recently.  I've been updating the important ones, but not updating all of them as the task is too big for me.  There's been a recent push by some volunteers to make updating them easier, but that hasn't made updating them happen.

Sugar 0.112 is the most stable version.  Investigate those fail to start or crashed activities using the Log activity, or by reading files in `.sugar/default/logs`.

**Comment by quozl** [comment]
Also, if you have another computer working fine, such as the one you are writing with, you can check to see if the same problems occur there by using VirtualBox, Parallels or VMware to run the same live build in a virtual machine.  That will help to isolate your problems as hardware cause.

**Comment by risole** [comment]
Thanks for the suggestions. I ran hp's hardware diagnostics (looping until error) for 13 hours last night and the utility reported zero errors after 5 or 6 full tests. However, it was behaving strangely even in windows 10, and today I returned the laptop to the store (it also had a temperamental trackpad click function and some other hardware issues; I couldn't consistently get it to start in safe mode and I was routinely getting the black screen of death after logging in). I wouldn't be surprised if the hp hardware diagnostic results were misleading. I was not able to test the memory with memtest86+ as the live build option to do so from grub did not actually start the memory testing utility, but instead, returned immediately to the grub boot loader screen, allowing me to try and start the utility again (probably a hardware problem?). I'm going to try this live build in virtualbox and in another laptop and I'll report findings here when I do.

**Comment by quozl** [comment]
Thanks for the update.  Every now and then very new hardware doesn't work very well with Linux, because manufacturers do something advanced for which they need special support.  The hardware diagnostics might be right, and Fedora and SoaS might be missing a driver, firmware or settings specific to the hardware.  Or the hardware diagnostics might not be representative of the pattern of CPU and RAM use that Windows 10 or Linux placed on the system.  Odd that memtest86+ would not run.

**Comment by risole** [comment]
Now working with the http://people.sugarlabs.org/~quozl/sugar-live-build-20171009/ live image on a Lenovo N23 80UR N3060 4G. Same behavior regarding memtest86+ with this new machine as I experienced with the hp laptop. Is it safe to conclude this is a software problem then?

I'm going to try installing to hard drive next, but just curious about the memtest86+ result.

**Comment by quozl** [comment]
Possibly.  Check with the Debian project about their Live Build, they'll know for sure.  We did nothing to include memtest86+ ourselves, it was just the default when building an image.  You might try another version of memtest86+ from a different distribution.
