### ISSUE TITLE
Home view activity start-new using Alt key does not work

### ISSUE THREAD

**Issue by quozl** [sugarlabs/sugar#780]
Reproducer: start an activity, stop it, view the home view activity ring, observe the activity icon now has user colour, press and hold the `alt` key, observe that user colour is removed, click on the icon, release the `alt` key. 

Expected result; activity is started new.

Observed result; no response, no errors logged.

Workaround; right-click, choose start new.

Does not occur on Fedora 18.

Does occur on Ubuntu 16.04, and 18.04 beta.

**Comment by Pro-Panda** [comment]
@quozl I would like to work on it

**Comment by quozl** [comment]
@Pro-Panda, there was an e-mail to me from GitHub saying you would like to work on this, but the comment is missing from this issue.  Is this a regression of GitHub, or did you delete?  If you deleted, was there something ambiguous about the issue that needs more details?

**Comment by Pro-Panda** [comment]
@quozl 
I deleted and forgot to write the updated one. Sorry
So this was what I found:
 - `alt+click` is **not** handled by **any** layer of `button-press-event` or any other signal in Sugar. Hence this
> Observed result; no response, no errors logged. 
 - It then goes to the underlying OS(on Ubuntu 16.04) and is used to move the window(rdesktop) by dragging the mouse
 - II am trying to override it in the same way as Alt+Tab is done.

Do you think I might be on the correct lines ?

**Comment by quozl** [comment]
No, wrong lines altogether.  [`HomeWindow.__key_press_event_cb`](https://github.com/sugarlabs/sugar/blob/master/src/jarabe/desktop/homewindow.py#L185) is where the `alt` key press is detected, and it saves state using `set_resume_mode`; a method of `HomeBox`.

**Comment by Pro-Panda** [comment]
@quozl Sorry, my previous statement might be ambiguous.
This is what I found.
While reproducing the issue,
1. Press `alt`: detected by `HomeWindow.__key_press_event_cb`
2. Keep holding `alt`
3. Clicking on any button after that; `button-press-event` is not detected by any layer of widgets via any signal
4. Release `alt`: detected by `HomeWindow.__key_release_event_cb`

**Proposed Reason** - Mouse cursor changes during 3 to one of dragging the window(rdesktop), as thats a feature of Ubuntu provided for any window
**Supporting Statement** - I couldn't reproduce this issue when I log into Sugar Desktop Environment instead of Ubuntu Desktop Environment itself(no redesktop). It creates a new activity in that case.

**Comment by quozl** [comment]
Thanks for the investigation.  I agree.  For me, symptom only occurs on VM (virt-manager, VirtualBox) under wmaker, and there is no change of cursor image, but the virtual machine window can be dragged.

Symptom does not occur on native hardware.
