### ISSUE TITLE
For new Sugar users

### ISSUE THREAD

**Issue by worldinmyfist** [sugarlabs/sugar#874]
Enhancement:
To make a text file available to new Sugar users, so that they get to learn Sugar DE very fast because this is basically for students.

**Comment by worldinmyfist** [comment]
Also i want to work on this issue if approved

**Comment by quozl** [comment]
Thanks for offering.  There is work that can be done, but perhaps not in the way you expect.

Think about who these students are.  Sugar is designed for pre-literate children from age 5 onwards, which is why we use icons and discoverability in the user interface.  Text use is limited, but brief.  Text is translated into [several languages](https://translate.sugarlabs.org/).  See note below.

We have a hypertext file set, see the [Help Activity](https://github.com/sugarlabs/help-activity), and [help.sugarlabs.org](https://help.sugarlabs.org/).  See note below.

Help Activity can be started from the Home View by clicking on the question mark icon.  A browser is used to display the content.

Keyboard shortcut <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>h</kbd> opens the hypertext at a position relating to the context; e.g. the current activity.  A menu item in the Frame icon for the activities does the same.

Some activities (e.g. Implode, Terminal) have a question mark icon to display activity-specific help.

Things you can do;
* update the Help Activity with changes that have happened in Sugar that haven't yet happened in Help Activity,
* update the Help Activity with changes that have happened in activities,
* update the curated screenshots in the Help Activity,
* add activity-specific help to activities that need it.

Looking forward to your contribution!

Note: two of the Sugar Labs machines are down because of a network renumbering at MIT in Boston.  Both Help and Translation web services are affected.

**Comment by worldinmyfist** [comment]
Thanks

**Comment by deejoe** [comment]
@worldinmyfist 

Are @quozl's suggestions sufficient so that we can close this issue and you can pursue your interest in helping with documentation elsewhere?

**Comment by worldinmyfist** [comment]
Yes
