### ISSUE TITLE
Sugar on a Stick on Raspberry Pi hangs on "A start job is running for /dev/"

### ISSUE THREAD

**Issue by acc3ssd** [sugarlabs/sugar#876]
I'm trying to install Sugar on a Stick on a Raspberry Pi 3B, but when I try to boot it, it hangs saying: "A start job is running for /dev/dis..." followed by a sting of characters and then the amount of time it's been running. I tried letting it run for an hour, but it did not proceed to the setup wizard.

I downloaded the Fedora image and verified the checksum. I've tried writing the image using Etcher and dd. I've also tried resizing the root partition before booting it. Every time I run into the same problem. I checked the /etc/fstab on the SD card and all the UUIDs seem to line up. Does anyone know what the problem might be?

**Comment by quozl** [comment]
Which version of Fedora?  Last I heard, the Fedora 30 version did something like this, but the Fedora 31 version yet to be released seems to have fixed it.

**Comment by acc3ssd** [comment]
Fedora 30. I downloaded the Sugar on a Stick image from https://arm.fedoraproject.org/.

Do you know what the workaround to this issue is?

**Comment by quozl** [comment]
One workaround is to install another of the Fedora 30 images, and then use our [instructions to install Sugar on Fedora](https://github.com/sugarlabs/sugar/blob/master/docs/fedora.md).

Another workaround is to install Raspian and then use our [instructions to install Sugar on Debian](https://github.com/sugarlabs/sugar/blob/master/docs/debian.md) since Raspbian is derived from Debian.

I don't recall the exact details of the fault you've hit, but I've found the discussion we had about it, see [mailing list archives for May 2019](http://lists.sugarlabs.org/archive/sugar-devel/2019-May/thread.html) for the subject _f30 arm soas now not working and a fix exists_.  See [1711475](https://bugzilla.redhat.com/show_bug.cgi?id=1711475) for the details.  @aperezbios uploaded an updated image.

Root cause was _changes by Fedora outside Sugar_ combined with _nobody testing_.

**Comment by aperezbios** [comment]
Fedora 31 is literal days away from being released in final form. Try this, the most recent F31 nightly: https://kojipkgs.fedoraproject.org/compose/branched/Fedora-31-20191010.n.0/compose/Spins/armhfp/images/Fedora-Minimal-armhfp-31-20191010.n.0-sda.raw.xz

**Comment by acc3ssd** [comment]
Thank you both very much for providing me with all these options. This was very helpful!

I ended up flashing the Fedora 31 image and it booted like a charm.

**Comment by quozl** [comment]
Thanks for testing.

**Comment by acc3ssd** [comment]
For reference, replacing the initramfs on the Fedora 30 image with the one downloaded from [here](https://fedorapeople.org/~pwhalen/soas/initramfs-5.0.9-301.fc30.armv7hl.img) also worked.

Fedora 31 was completely unstable on my Raspberry Pi 3B. I couldn't work in X Windows for more than five minutes without the whole system freezing. I couldn't find any relevant entries in the logs, so I decided to try Fedora 30 again. So far, it seems to be stable.

Thanks again for all your help.

**Comment by quozl** [comment]
Thanks for letting us know.  Unfortunate that Fedora 31 was so unstable.  Perhaps tell the Fedora people about it.

**Comment by acc3ssd** [comment]
That's a good idea, thanks.
