### ISSUE TITLE
[Q] Suspected missing character

### ISSUE THREAD

**Issue by srevinsaju** [sugarlabs/sugar#890]
```
sudo apt update
for module in sugar{-datastore,-artwork,-toolkit,-toolkit-gtk3,}; do
    sudo apt build-dep $module
done
sudo apt install python{,3}-six python3-empy
```

In the last line, is it supposed to be
```
sudo apt install python{2,3}-six python3-empy
```
Or is it a perceived mistake? I am not into Regex

~ GCI

**Comment by quozl** [comment]
Thanks for asking.  The package names on Ubuntu for Six are _python-six_ and _python3-six_, because they follow the Debian convention or standard for package names.  It is not a regexp, but an expansion.  The documentation for **bash(1)** has a section "Brace Expansion" which shows how this is used.  You can test brace expansion using the shell like this;

```bash
echo python{,3}-six
```
