### ISSUE TITLE
"No module named gst" in Debian 10.2

### ISSUE THREAD

**Issue by pelacables** [sugarlabs/sugar#900]
Hi all,

According to sugar docs, Sugar 0.112 is availale in Buster release.

So I've installed DebianEdu (10.2) and most of the activities (installed from the browser) fail to start with the error:
```bash
ImportError: No module named gst
```

I have python-gst-1.0 installed in my system. From what I read (and understood, I can be totally wrong) gst is the module provided by gstreamer0.10-*. In newer version 1.0 it has to be imported like:

```bash
import gi
gi.require_version('Gst', '1.0')
from gi.repository import Gst
```

Does it mean that I have to install Debian 9 or is there a workaround for making the activities work in Buster?

TIA,
Arnau

**Comment by quozl** [comment]
Thanks for asking.  It depends on each activity.  Please identify them?  Browse has an old link to activities.sugarlabs.org, which is used for activities dependent on Python 2, GStreamer 0.1, WebKit, and either GTK 2 or GTK 3.  Yes, install an older Debian release or GStreamer 0.1 if you want these older activities to work.  Otherwise use a later version of the activities.  It is a disorganised mess because we don't have people working on a replacement for the app store function.  People have tried, but they haven't been willing to fix the [bugs](https://github.com/sugarlabs/aslo) in activities.sugarlabs.org that would separate activities by version, or [provide bundles suitable to the client](https://github.com/sugarlabs/aslo-v3/issues/14#issuecomment-459098830).  When I release activities my bundles are uploaded to http://people.sugarlabs.org/~quozl/ but whether they will work for Debian 10.2 will vary.

**Comment by pelacables** [comment]
Hi, sorry for the late answer.

Thanks a lot, I'll look for the activities I want for the newer Debian version and, if I don't find them, I'll install and older Debian release.

Thanks a lot for your answer. I  close thi ticket.
