### ISSUE TITLE
Issues not labelled

### ISSUE THREAD

**Issue by ShubhikaBhardwaj** [sugarlabs/sugar#917]
-None of the issues are labelled based on the difficulty levels like-beginner,medium,hard.
-Issues should also be labelled as bug,enhancement,new feature etc.
-Make issues more readable and beginner friendly

**Comment by ShubhikaBhardwaj** [comment]
@quozl Hi James! Could you help me in labeling these issues for future contributors.

**Comment by quozl** [comment]
No thanks.

Issues are for reporting problems you don't plan to fix, in the hope that someone else will fix them.

Issues rarely have a known fix.  If I knew how to fix an issue, I fix it immediately.  Cheaper than bothering everyone with notifications, and having to track the issue.

An assessment of difficulty levels can only arise from a "known fix".  Moving an issue from "unknown fix" to "known fix" is the first stage of problem solving, and is the most costly stage.  Doing that stage for every issue _without fixing the issue_ or even _explaining how to fix it_ is setting up a beginner to fail.

Also, what is easy or hard for me is certainly not easy or hard for anyone else.

Also, adding labels or more comments to issues just creates notification noise and activity pollution, making it harder for the issue to be understood.

If an issue is hard to understand, ask questions about it.  If anyone is still interested in the issue, they can answer.  If the issue owner is still available, they can edit their comment and then hide the questions.  If questions continue to go unanswered, then it's time to close the issue because nobody has an interest in it any more.

Overall, I fix things properly rather than leave little bugs for beginners to chew on.  It would be professionally embarrassing to do otherwise.  :grinning:

**Comment by srevinsaju** [comment]
Interesting issue to manager other issues.

One of few **easy** issues to be fixed might be to add **documentation** as anyone can do it in any circumstances with proper language skills. Maybe we could add the `good first issue` for any documentation related issues. I started learning about Sugar Environment by writing documentation.

**Comment by quozl** [comment]
It may never close though.  Perhaps I should put it in [Projects](https://github.com/orgs/sugarlabs/projects).  @ShubhikaBhardwaj, did you look at Projects?

**Comment by ShubhikaBhardwaj** [comment]
@srevinsaju I am glad you understood my point. Adding 'good first issue'would be a good idea.

**Comment by ShubhikaBhardwaj** [comment]
@quozl I agree with you too! When it comes to "unknown issues", it might actually be a cumbersome task and the noise can actually be bad.

**Comment by quozl** [comment]
@ShubhikaBhardwaj, did you look at Projects?

**Comment by ShubhikaBhardwaj** [comment]
@quozl I haven't looked at the projects yet! However, it would be good to add it as a new project.

**Comment by quozl** [comment]
@ShubhikaBhardwaj, also, our new developer induction process is handled through the sugar-devel@ mailing list subscription.  When you subscribe, you get a welcome message detailing a lot of options.  Did you subscribe?  Your profile doesn't have your mail address, so I can't check.

**Comment by ShubhikaBhardwaj** [comment]
"Issues have not been created, as it is a waste of time to do so." Hey..I found this quoted under every project description. Are you suggesting that contributors should work on projects rather than tiny issues and, create or fix issues -only if needed.

**Comment by ShubhikaBhardwaj** [comment]
@quozl I had subscribed to SugarLabs mailing list last year. It should show,perhaps.

**Comment by quozl** [comment]
I'm suggesting that as we have a project, we don't need an issue created, just a pull request.  Also mirrors what I said above, about issues being problems that we don't plan to fix and are looking for others to fix them.  I found your subscription, it was in March last year.  I'm not sure you got the greeting, I'll send it.

**Comment by ShubhikaBhardwaj** [comment]
@quozl Okay! That's great. I would like to work on a project and would be glad to send you a PR. However, I am not a GSSOC participant for this year. I am an open source contributor, keen working Web Development or ML related projects at SugarLabs. What's the way to move forward from here?

**Comment by ShubhikaBhardwaj** [comment]
I just got the greeting! Thanks for that :)

**Comment by ShubhikaBhardwaj** [comment]
@quozl  I am not a GSOC participant for this year. Can I still contribute?

**Comment by quozl** [comment]
Yes, you can certainly contribute.  We don't restrict contribution while GSoC is on.  We might be busy, but we will eventually cooperate if the contribution is beneficial.

However, we don't have any machine learning needs.  Web development with JavaScript knowledge only you can look at JavaScript activities for Sugarizer or Sugar.  Should you have JavaScript and good Python knowledge, there are Sugar integration issues with JavaScript activities that need investigating.

But as I say at the end of my induction letter, we do assume you will be self-directed.  We won't give you tasks to do; you have to figure out what tasks you should do yourselves.  That's exactly what we do.  Totally fair.

**Comment by ShubhikaBhardwaj** [comment]
@quozl Thanks for the lead.I will be self-directed!
