### ISSUE TITLE
Language control panel fails to open with Sugar 0.118

### ISSUE THREAD

**Issue by aperezbios** [sugarlabs/sugar#941]
On a nightly build of Fedora SoaS, with 0.118 for all packages, the Language control panel does not open, and the shell.log has a message stating "AttributeError: 'NoneType' object has no attribute 'needs_restart'"

**Comment by aperezbios** [comment]
`  File "/usr/lib/python3.9/site-packages/jarabe/controlpanel/gui.py", line 383, in __accept_clicked_cb
    if self._section_view.needs_restart:
AttributeError: 'NoneType' object has no attribute 'needs_restart'`

**Comment by aperezbios** [comment]
This is the Fedora nightly ISO I tested with, which is 1.06GB in size: https://www.dropbox.com/s/kdry595y0s7ae0a/Fedora-SoaS-Live-x86_64-Rawhide-20210208.n.0.iso?dl=0

**Comment by quozl** [comment]
Thanks.  7bbff9f59 ("Deepsource: unnecessary `else` or `elif`") was the most recent change, and was preceded by ea2cd9c7b ("Fix Gtk-WARNING in language control panel").

Each control panel is an extension that is imported with exceptions handled so that Sugar does not terminate when a buggy extension is added.  When regressions occur in extensions, the cause is hidden.  I suggest;

* check shell.log for an earlier messages during loading of the extension,
* temporarily turn off the exception handler in src/jarabe/controlpanel/cmd.py load_modules.

**Comment by aperezbios** [comment]
Thanks, Walter. I've applied this patch manually and confirmed that it fixes the problem. I'm able to successfully switch languages to Spanish, and then back to English.
