### ISSUE TITLE
How to login to sugar on raspbian ?

### ISSUE THREAD

**Issue by dinegredin** [sugarlabs/sugar#985]
Hello,
I've installed sugar on may raspberry pi3b running the last version of raspberry OS 
Using those instructions : 

sudo apt install sucrose lightdm

but i cannot find the way to launch sugar.
When i log out there is no other proposition than my default account to log back into.
What am i missing ?
Thanks for your help

**Comment by quozl** [comment]
It's not a different account to log in to, but a different desktop choice.  How this is presented depends on the greeter, which is the software that prompts for your username and password.  I tested this a few weeks ago, and the option to select desktop appeared only while password was being entered.  I think it was a gear wheel icon.  Please identify the version of Raspberry Pi OS you used; it is important to understand that if we are to reproduce, and saying "latest" doesn't help, because new releases of Raspberry Pi OS do happen.

How did you install Sugar?

**Comment by dinegredin** [comment]
Thanks for your answer !
My version of raspbian is "Raspbian GNU/Linux 11 (bullseye)"
I've installed sugar using this command :
sudo apt install sucrose lightdm
I found those instructions on this page  :
https://github.com/sugarlabs/sugar/blob/master/docs/debian.md

When i enter my password there's no change on the login page

Does it mean that i have to select another greeter ?

**Comment by walterbender** [comment]
Try James's suggestion: Log out and then click on your login name. You should see a Password Prompt and a "gear" icon (probably in the corner of the screen). Click on the gear and you should see a menu of desktop options, one of which should be Sugar. Note that to get back to Gnome or other desktop choices, you'll have to repeat these steps after logging out of Sugar.

**Comment by dinegredin** [comment]
I've tried but there is no gear unfortunately .
My login page looks like this 
![image](https://github.com/sugarlabs/sugar/assets/55543721/a9c6b0cc-604c-4919-8b65-beab5197bb5a)

**Comment by quozl** [comment]
That's certainly not the latest.  See https://www.raspberrypi.com/software/operating-systems/ which shows most recent release 15th March based on Debian Bookworm, not Bullseye.

I suggest you upgrade.

If you can't, ... that photograph does not look like lightdm, but like the previous display manager that Raspberry Pi OS began with.

I suggest you do this;
* set up remote SSH access with raspi-config and then SSH into the Raspberry Pi from another system,
* get the Raspberry Pi display to the greeter prompt as you showed us,
* use the `ps axfww` command to capture the process list,
* look for the greeter process in order to identify it,
* use the source code for the greeter to understand how it works and reconfigure it.

See the page https://github.com/sugarlabs/sugar-docs/blob/master/src/sugar-logging-in.md for alternate display managers and how they look.

**Comment by dinegredin** [comment]
Hello thanks for your help.
I finally made it work by changing the default greeter.
I followed the instructions on this video ( from timecode 3:00 )
https://www.youtube.com/watch?v=IEtkzVKJP-M

Unfortunately  sugar OS doesn't work very well on my Raspberry Pi 3B it lags a lot some activities i've downloaded won't open so i guess it is not the best platform to use it on.

Nevertheless all the developer that made Sugar deserved a big thanks 🙏 

Have a nice day
